import "./globals.css";
import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation";
import SearchBar from "@/components/SearchBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen">
          <Navigation />
          <SearchBar />
          {children}
        </main>
      </body>
    </html>
  );
}

/* <body className={inter.className}> */
