import "./globals.css";
import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation";
import Providers from "@/store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <main className="min-h-screen">
            <Navigation />
            {children}
          </main>
        </body>
      </Providers>
    </html>
  );
}
